### ISSUE TITLE
No license specified :(

### ISSUE THREAD

**Issue by sgbeal** [ccxvii/minilibs#1]
i'm _really_ interested in using your regex library in a piece of software but i can find no license for the sources anywhere in this tree, which means i can't include these sources in my (public domain) trees.

Can you please specify the license conditions for this code (ideally in each header file)?

**Comment by ccxvii** [comment]
The README file says they're public domain.

If you're specifically looking for the regular expression library, I recommend you take the more up to date copy I use in mujs, which also has a more explicit ISC license. It's the same code, but with bug fixes I haven't had time to backport to here yet, and unicode support.

https://github.com/ccxvii/mujs/

**Comment by sgbeal** [comment]
Fantastic, thank you! My apologies, i missed the first sentence in the readme because my eyes were looking for the word "license" :/.
